services:
  app:
    image: ghcr.io/42-gy/ft_cabinet_be/app:latest
    restart: always
    ports:
      - "80:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - FT_CLIENT_ID=${FT_CLIENT_ID}
      - FT_CLIENT_SECRET=${FT_CLIENT_SECRET}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - AI_SERVER_URL=http://ai:8000
      - COOKIE_SECURE=${COOKIE_SECURE}
      - TZ=Asia/Seoul
      - CORS_ALLOWED_ORIGINS=https://ft-cabinet-server.azurewebsites.net
    depends_on:
      - db
      - redis
      - ai
    deploy:
      resources:
        limits:
          memory: 1.5G

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_DATABASE: cabi
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          memory: 700M

  redis:
    image: redis:alpine
    restart: always
    deploy:
      resources:
        limits:
          memory: 300M

  ai:
    image: ghcr.io/42-gy/ft_cabinet_ai:latest
    restart: always
    environment:
      - MODEL_PATH=models/efficientNetV2-S-v1.1.0.keras
    deploy:
      resources:
        limits:
          memory: 1.2G

volumes:
  db_data:
