services:
  app:
    image: ghcr.io/42-gy/ft_cabinet_be/app:latest
    restart: always
    ports:
      - "80:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - FT_CLIENT_ID=${FT_CLIENT_ID}
      - FT_CLIENT_SECRET=${FT_CLIENT_SECRET}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - AI_SERVER_URL=http://${AI_HOST}:8000
      - COOKIE_SECURE=${COOKIE_SECURE}
      - TZ=Asia/Seoul
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    depends_on:
      - db
      - redis
      - ai

  db:
    image: mariadb:10.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  ai:
    image: ghcr.io/42-gy/ft_cabinet_ai:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=${AI_MODEL_PATH}
