server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

spring:
  config:
    import: optional:file:src/main/resources/secret.properties

  application:
    name: 42cabi-gyeongsan

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/cabi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: CabiHikariPool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        registration:
          42:
            client-id: ${FT_CLIENT_ID}
            client-secret: ${FT_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: public
            client-name: 42 gyeongsan
        provider:
          42:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: login

cabinet:
  policy:
    lent-term: 30
    extension-term: 15
  items:
    extension-price: 1000
    swap-price: 100
    penalty-exemption-price: 600

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    groups-order: desc
    disable-swagger-default-url: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, graphics, metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${jwt.secret}

slack:
  token: ${SLACK_BOT_TOKEN}

ai:
  server:
    url: https://cameron-hereditary-suppositively.ngrok-free.dev/predict

app:
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000,https://d1cgxw6sqqa9fo.cloudfront.net"

resilience4j:
  circuitbreaker:
    instances:
      aiServer:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 5
  ratelimiter:
    instances:
      ftApi:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 5s